language: objective-c

before_install:
- brew update
- brew outdated xctool || brew upgrade xctool

script: 
- xctool -sdk iphonesimulator -workspace LPDMvvmKit.xcworkspace -scheme LPDMvvmKit clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
